name: System Monitor
on:
  schedule:
  - cron: '0 0 1 * *' #Every month
jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install psutil
      - run: python3 system.monitor.py